### ISSUE TITLE
vxtwitter.com and fxtwitter.com

### ISSUE THREAD

**Issue by ignoramous** [PeterDaveHello/url-shorteners#16]
Not url shorteners but are url redirectors folks typically use to "fix" twitter-video embeds in Discord, apparently.

Does that make it eligible for this blocklist? 

FxTwitter: https://github.com/robinuniverse/TwitFix
VxTwitter: https://github.com/dylanpdx/BetterTwitFix

**Comment by PeterDaveHello** [comment]
@ignoramous Thanks, will take a look and see how's it fitting.

Actually, I'm trying to write kind of definition of URL shortener(that will be listed) here, so that it will be clear that what should be added or not.

Give me a couple of days, thanks again for your contribution!

**Comment by PeterDaveHello** [comment]
As you can simply confirm its content behind, it doesn't use an encoding algorithm to hide the original URL or path, and the intention is not to shorten the URL, should not treat the service as URL shortener ;)
