### ISSUE TITLE
gtly.to gtly.ink gtly.io used by geotargetly.com

### ISSUE THREAD

**Issue by geotargetly** [PeterDaveHello/url-shorteners#19]
Hello,

Please add the following domains to this list. We utilize these domains as URL shorteners for our Geo Links service at [Geotargetly](https://geotargetly.com/geo-link). We are a genuine URL-shortening service with built-in geolocation routing.

gtly.to
gtly.ink
gtly.io

Thank you :)

**Comment by PeterDaveHello** [comment]
@geotargetly thanks for information, would you like to send a pull request for those domains? So we can get them added as soon as possible, thank you.

**Comment by PeterDaveHello** [comment]
#20 merged, thanks!
