### ISSUE TITLE
RDNS blocklist inclusion

### ISSUE THREAD

**Issue by shuvashish76** [PeterDaveHello/url-shorteners#2]
Request to include this blocklist to https://rethinkdns.com/configure
Source code: https://github.com/serverless-dns/blocklists

ThankYou

**Comment by PeterDaveHello** [comment]
I'd see what I can do. Thanks.

**Comment by PeterDaveHello** [comment]
@shuvashish76 looks good enough to you? I'm not familiar with RethinkDNS's blocklist, hope it works.

https://github.com/serverless-dns/blocklists/pull/47
