### ISSUE TITLE
Please add hopp.to

### ISSUE THREAD

**Issue by shaulgo** [PeterDaveHello/url-shorteners#22]
Hey,

Hopp.to is a url shortner (also a link-in-bio website builder). 
Can you please add it to the whitelist? 

Thanks

**Comment by PeterDaveHello** [comment]
I only see hopp.to being used with different subdomains, doesn't look like a URL shortener on the domain itself, would like to see some examples if you got some.

**Comment by shaulgo** [comment]
We have both url shorteners and landing pages in this product and using the hopp.to domain.

url shortener
format: [user].hopp.to/[customName]
example: https://shaul.hopp.to/google2
landing page -
format: hopp.to/[user]
example: https://www.hopp.to/shaul
