### ISSUE TITLE
Add lnk.bio

### ISSUE THREAD

**Issue by ignoramous** [PeterDaveHello/url-shorteners#29]
Ex: https://archive.is/f5Bm8

**Comment by PeterDaveHello** [comment]
@ignoramous would you mind directly provide the source and target link in the issue? Thanks.

**Comment by ignoramous** [comment]
Sure: Is this what you're looking for?

Source: `https://lnk.bio/go?d=https://verse-technology.com/&hash=2f6e190dbce81f39eb15407c4c84dc51&id=4709123&ext=-1603635&timezone=America/New_York&type=1`

Target: `https://verse-technology.com`

**Comment by PeterDaveHello** [comment]
@ignoramous https://lnk.bio/go?d=https://xxx.xxx looks more like redirection, not short url? I mean like goo.gl/xxxx -> example.com/a-long-link

**Comment by ignoramous** [comment]
Though I can't seem to find the short link for the target above... `lnk.bio` *does* have short-url support too: [`help.lnk.bio/en/articles/4189739-story-links-how-do-i-use-them`](https://archive.is/8KRhk). [`https://help.lnk.bio/en/articles/4189739-story-links-how-do-i-use-them`](https://archive.is/aQbiI).

**Comment by PeterDaveHello** [comment]
@ignoramous I only found those don't look like short url, checked many, only list a few:

https://lnk.bio/JaxCuy
https://lnk.bio/v09K
https://lnk.bio/v09K

**Comment by ignoramous** [comment]
I guess we can close this for now until we find `lnk.bio` short-link redirects.

**Comment by PeterDaveHello** [comment]
@ignoramous sure
