### ISSUE TITLE
Add app.link

### ISSUE THREAD

**Issue by ignoramous** [PeterDaveHello/url-shorteners#30]
Ex: https://archive.is/EOKzq

Source: `https://depop.app.link/linktreedepopexplorepage`

Target: `https://www.depop.com/?_branch_match_id=1188516830733007005&utm_source=Instagram&utm_campaign=Linktree&utm_medium=Social&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXT0ktyC/QSywo0MvJzMvWBxElRampYOHUioKc/KLUgsT0VACVSs/0LwAAAA%3D%3D`

**Comment by PeterDaveHello** [comment]
Do we have those records on just app.link, instead of bunch of subdomains?

A little bit similar with the gtly.io case in #20

**Comment by ignoramous** [comment]
I couldn't find any, but I personally consider these domains as shorteners. For instance, `bitly` also supports redirects too, but its blocked by this list anyway.

**Comment by ignoramous** [comment]
Debatable whether it is a link shortener. Closing...
