### ISSUE TITLE
Add caro.sl

### ISSUE THREAD

**Issue by ignoramous** [PeterDaveHello/url-shorteners#32]
See: https://archive.is/q11FD (the link in the twitter handle)

[`caro.sl`](https://archive.is/BqwLC) is powered by bitly (as of writing)

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
Looks seem to be working:

- https://caro.sl/2IXUoEq
- https://caro.sl/app
- https://caro.sl/caroupay/help
- https://caro.sl/Carouselland2017
- https://caro.sl/contact-carousell
- https://caro.sl/FamilySurvivalPack
- https://caro.sl/feb-2020-promotion-1b
- https://caro.sl/newlook
