### ISSUE TITLE
Add mnge.co

### ISSUE THREAD

**Issue by ignoramous** [PeterDaveHello/url-shorteners#51]
Source: `u3.mnge.co/nZNE9xP`

Target: `https://healthplus.flipkart.com/?_branch_match_id=1095686424984783326&utm_source=aia_fallback&utm_medium=CRM&_branch_referrer=H4sIAAAAAAAAA8soKSkottLXT8vOKMgpLdZLLCjQy8nMy9Y3DDWIKss0dfYsSwIA9x6RLyQAAAA%3D`

Ex: https://archive.is/KtFC4

**Comment by PeterDaveHello** [comment]
@ignoramous would you like to send pull requests for those suggestions? Thanks.

**Comment by ignoramous** [comment]
Sure: https://github.com/PeterDaveHello/url-shorteners/pull/52

And about other open PRs ;) Ex: https://github.com/PeterDaveHello/url-shorteners/pull/15

**Comment by ignoramous** [comment]
`mnge.co` is not an exact match for a link shortener. Closing...
