### ISSUE TITLE
add goo.su

### ISSUE THREAD

**Issue by ignoramous** [PeterDaveHello/url-shorteners#66]
Ref: https://archive.is/1XVhe

Source: `goo.su/uteit`

Target: `https://impact-mission.org/courses/sustainable-leadership-impact-management/?ysclid=lq21afjg45902389974`

**Comment by PeterDaveHello** [comment]
It's already added since ca8ed7cfa09ec04e17d81840728247ffa02fbe35

**Comment by ignoramous** [comment]
My bad... thanks.
