### ISSUE TITLE
Add `go-link.ru`

### ISSUE THREAD

**Issue by TheUnsocialEngineer** [PeterDaveHello/url-shorteners#81]
u.to
go-link.ru

**Comment by TheUnsocialEngineer** [comment]
both shorteners being used for scams, u.to is already in the list but go-link.ru isnt added yet, would like go-link.ru to be added for use in blacklisting

**Comment by PeterDaveHello** [comment]
Please note that this is not a scam domain list, but url-shortener list, though I still found some working examples that can be used to add the domain:

- `https://go-link.ru/jAV7W`
- `https://go-link.ru/o6E5M`
- `https://go-link.ru/o0qlE`
- `https://go-link.ru/oERO4`
- `https://go-link.ru/mNGNa`
- `https://go-link.ru/mBdpE`

Those domains are from the Internet, and I don't know what the content is, so please take your own risks to open it.
